name: test

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Event File
        path: ${{ github.event_path }}
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      
      - name: Install Python dependencies
        run: pip install -r tests/requirements.txt
      
      - name: Run tests
        run: pytest --junitxml=junit/test-results.xml
      
      - name: Upload Test Results
        if: (!cancelled())
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: |
            junit/*.xml
