name: test

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      
      - name: Install Python dependencies
        run: pip install -r tests/requirements.txt
      
      - name: Run tests
        run: pytest --junitxml=junit/test-results.xml
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: |
            junit/**/*.xml
